version: "3.5"
services:
  orion:
    image: fiware/orion-ld
    hostname: orion
    container_name: fiware-orion
    expose:
    - "1026"
    ports:
    - "1026:1026"   
    depends_on:
    - mongo-db
    command: -dbhost mongo-db -logLevel DEBUG
    environment:
    - ORIONLD_CONN_MEMORY=1024

  mongo-db:
    image: mongo:3.6
    hostname: mongo-db
    container_name: db-mongo
    expose:
    - "27017"
    ports:
    - "27017:27017"
    #networks:
    #- default
    command: --nojournal
    volumes:
    - mongo-db:/data

volumes:
  mongo-db: ~

